FROM golang:1.25 AS builder

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -trimpath -ldflags='-s -w' -o /infracost-controller ./cmd/controller

FROM gcr.io/distroless/static-debian12:nonroot

COPY --from=builder /infracost-controller /usr/local/bin/infracost-controller
ENTRYPOINT ["/usr/local/bin/infracost-controller"]
