apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-collector
  labels:
    app.kubernetes.io/name: infracost-collector
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: infracost-collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: infracost-collector
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: collector
          image: "{{ .Values.collector.image.repository }}:{{ .Values.collector.image.tag }}"
          imagePullPolicy: {{ .Values.collector.image.pullPolicy }}
          resources:
            {{- toYaml .Values.collector.resources | nindent 12 }}
          volumeMounts:
            - name: pod-resources
              mountPath: /var/lib/kubelet/pod-resources
              readOnly: true
      volumes:
        - name: pod-resources
          hostPath:
            path: /var/lib/kubelet/pod-resources
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
