apiVersion: v1
kind: Service
metadata:
  name: {{ include "infracost.fullname" . }}-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "infracost.collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.collector.service.type }}
  ports:
    - port: {{ .Values.collector.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "infracost.collector.selectorLabels" . | nindent 4 }}
